default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ezscheduler
  password: ezscheduler

development:
  <<: *default
  database: ezscheduler_development
test:
  <<: *default
  database: ezscheduler_test

production:
  <<: *default
  database: ezscheduler_production
  username: ezscheduler
  password: <%= ENV['EZSCHEDULER_DATABASE_PASSWORD'] %>
